### ISSUE TITLE
[Help] create custom component with textfield and select

### ISSUE THREAD

**Issue by ahka01** [formio/contrib#24] opened 2022-03-17 09:16 UTC
Hi all,

I'm willing to create a custom component that includes an entry field and drop-down list next to it, for example to choose the language or the unit of the entered text.

Could you please give me some hints how to tackle this task?

Concrete, I would like to know the following:
1. from which component to derive? Container?
2. how to use renderTemplate and pass textfield and select objects to it?

I'm struggling with it since days, and don't know how to move forward!

Thanks and regards

**Comment by 0liver** [comment] 2022-10-27 11:56
This is not a bug you've found, so the bug label should not be on it.

For a quick start, skipping all of the ceremony, build pipeline, formiojs dependency and what now, see [this comment here](https://github.com/formio/contrib/issues/2#issuecomment-628209833).

**Comment by daneformio** [comment] 2024-02-14 14:31
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!

**Closed by daneformio** 2024-02-14 14:31 UTC
Labels: bug
